language: go

go:
  - 1.1
  - 1.4

before_script:
  - sed -i "s/mitchellh\/packer/henrysher\/packer/g" `find . -name "*.go"`
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi

script:
  - go test -v ./...
